#!/bin/bash
rm -rf var/ etc/ init.el
emacs --batch --eval "(require 'org)" --eval '(org-babel-tangle-file "~/emacs-configs/minimal-emacs/config.org")' && emacs --debug-init --init-directory ~/emacs-configs/minimal-emacs/
