;;; Automatically generated by ‘recentf’ on Thu Aug 13 05:47:36 2026  -*- mode: emacs-lisp; lexical-binding: t -*-

(setq recentf-list
      '(
        "~/Git/common/python/flake.nix"
        "~/Git/common/python/src/sample.py"
        "~/.config/emacs/config.org"
        "~/Git/common/python/tests"
        "~/.config/emacs/early-init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
