;;; Automatically generated by ‘recentf’ on Mon Aug 10 23:11:02 2026.

(setq recentf-list
      '(
        "~/Git/common/learning/python/src/sample3.py"
        "~/.config/emacs/config.org"
        "~/.config/emacs/config.bak/config.bak2.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
