;;; Automatically generated by ‘recentf’ on Sun Aug  9 07:30:50 2026  -*- mode: emacs-lisp; lexical-binding: t -*-

(setq recentf-list
      '(
        "~/.config/emacs/config.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
