;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-emacs-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(consult--buffer-history corfu-history evil-ex-search-history minibuffer-history vertico-repeat-history file-name-history extended-command-history evil-ex-history))
(setq consult--buffer-history '("*Messages*􀀀"))
(setq corfu-history '(":sample-face" "use-package"))
(setq evil-ex-search-history '("denote-citar-sections"))
(setq vertico-repeat-history '((ar/find-file-in-emacs-config "~/.config/emacs/" "config.org") (find-file "~/.config/emacs/etc/" "elpaca.eld") (ar/find-file-in-emacs-config "~/.config/emacs/etc/" "elpaca.eld") (ar/find-file-in-emacs-config "~/.config/emacs/config.org")))
(setq file-name-history '("~/.config/emacs/config.org" "~/.config/emacs/etc/elpaca.eld" "~/.config/emacs/config.org"))
(setq extended-command-history '("ghostel-download-module"))
(setq evil-ex-history '("w" "wq" "w" "q" "w" "q" "w" "q"))
(setq evil-jumps-history '((305577 #1="/home/ahsan/.config/emacs/config.org") (160582 #1#)))
(setq global-mark-ring 'nil)
(setq search-ring 'nil)
(setq regexp-search-ring 'nil)
